server:
  port: 7777
  max-http-header-size: 8192
spring:
    profiles:
      active: product
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/shareddoctor?characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=UTC
    application:
          name: mybatis-service
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database: mysql
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: UTC